[server]
enableXsrfProtection = false
enableCORS = false
maxUploadSize = 200

[theme]
base = "light"
primaryColor = "#5a9"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e0e2e6"
textColor = "#262730"

[font]
sansSerif = "Arial, sans-serif" 